# Generated by Django 5.2.11 on 2026-02-21 17:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0002_shop_address_shop_city_shop_country_shop_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sku', models.CharField(help_text="Code unique d'identification du produit", max_length=100, unique=True, verbose_name='Code SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code-barres')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image du produit')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text="Prix d'achat du produit", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Prix d'achat")),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Prix de vente du produit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix de vente')),
                ('unit', models.CharField(choices=[('piece', 'Pièce'), ('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('ml', 'Millilitre'), ('m', 'Mètre'), ('cm', 'Centimètre'), ('box', 'Boîte'), ('pack', 'Pack'), ('other', 'Autre')], default='piece', max_length=20, verbose_name='Unité de mesure')),
                ('minimum_stock', models.PositiveIntegerField(default=10, help_text='Alerte si stock en-dessous de cette valeur', verbose_name='Stock minimum')),
                ('reorder_level', models.PositiveIntegerField(default=20, help_text='Niveau recommandé pour commander', verbose_name='Niveau de réapprovisionnement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Produit actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('shop', models.ForeignKey(blank=True, help_text='Laisser vide si le produit est commun à toutes les boutiques', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'), models.Index(fields=['barcode'], name='products_pr_barcode_e44f4f_idx'), models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'), models.Index(fields=['shop'], name='products_pr_shop_id_6c5838_idx'), models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx')],
            },
        ),
    ]
