# Generated by Django 5.2.11 on 2026-03-24 01:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0002_shop_address_shop_city_shop_country_shop_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Journalière'), ('weekly', 'Hebdomadaire')], default='daily', max_length=10, verbose_name='Type de période')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Clôturée')], default='active', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_sessions', to='shops.shop', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('sale_date', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='sales.cashiersession', verbose_name='Session')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('sale_type', models.CharField(choices=[('direct', 'Vente directe'), ('delivery', 'Livraison')], default='direct', max_length=10, verbose_name='Type de vente')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('on_delivery', 'Paiement à la livraison')], default='cash', max_length=20, verbose_name='Moyen de paiement')),
                ('payment_status', models.CharField(choices=[('paid', 'Payé'), ('pending', 'En attente')], default='paid', max_length=10, verbose_name='Statut paiement')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Adresse de livraison')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livré le')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('completed', 'Complétée'), ('cancelled', 'Annulée')], default='completed', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_as_cashier', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Livreur')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.cashiersession', verbose_name='Session de caisse')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='shops.shop', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(blank=True, choices=[('fixed', 'Montant fixe'), ('percent', 'Pourcentage')], max_length=10, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='products.product', verbose_name='Produit')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
            },
        ),
        migrations.AddIndex(
            model_name='cashiersession',
            index=models.Index(fields=['shop', 'status'], name='sales_cashi_shop_id_14b839_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiersession',
            index=models.Index(fields=['cashier', 'status'], name='sales_cashi_cashier_37bdca_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiersession',
            index=models.Index(fields=['start_date', 'end_date'], name='sales_cashi_start_d_d2ab4f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['shop', 'sale_date'], name='sales_expen_shop_id_49e5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['session'], name='sales_expen_session_2ec818_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['shop', 'created_at'], name='sales_sale_shop_id_a0d636_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['session', 'created_at'], name='sales_sale_session_8bcde2_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['livreur', 'payment_status'], name='sales_sale_livreur_51a62b_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sales_sale_status_532843_idx'),
        ),
    ]
