# Generated by Django 5.2.11 on 2026-04-11 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('shops', '0004_backfill_managers_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='livreur_paid',
            field=models.BooleanField(default=False, verbose_name='Commission livreur payée'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['livreur', 'livreur_paid'], name='sales_sale_livreur_ff7399_idx'),
        ),
    ]
