# Generated by Django 5.2.11 on 2026-03-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('SHOP_MANAGER', 'Manager de Boutique'), ('EMPLOYEE', 'Employé'), ('LIVREUR', 'Livreur')], default='EMPLOYEE', max_length=20, verbose_name='Rôle'),
        ),
    ]
