# Generated by Django 5.2.11 on 2026-04-10 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_magasinier_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shops', '0003_multi_manager_and_shop_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_users', to='shops.shop', verbose_name='Boutique de rattachement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='shops.shop', verbose_name='Boutique courante'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['home_shop'], name='accounts_us_home_sh_c6bf94_idx'),
        ),
    ]
