# Generated by Django 5.2.11 on 2026-04-10 05:29

from django.db import migrations


def backfill_home_shop(apps, schema_editor):
    """home_shop = shop pour tous les users qui ont shop mais pas home_shop."""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.filter(home_shop__isnull=True, shop__isnull=False):
        user.home_shop_id = user.shop_id
        user.save(update_fields=['home_shop'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_home_shop'),
    ]

    operations = [
        migrations.RunPython(backfill_home_shop, migrations.RunPython.noop),
    ]
