# Generated by Django 5.2.11 on 2026-02-20 12:17

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(default='Bénin', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='shop',
            name='ifu',
            field=models.CharField(blank=True, help_text="Numéro d'identification fiscale", max_length=50, null=True, unique=True, verbose_name='IFU (Identifiant Fiscal Unique)'),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='shop',
            name='manager',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'SHOP_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_shop', to=settings.AUTH_USER_MODEL, verbose_name='Manager principal'),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BJ', verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='shop',
            name='slogan',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Boutique active'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom de la boutique'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['name'], name='shops_shop_name_da338f_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_active'], name='shops_shop_is_acti_bbb154_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['manager'], name='shops_shop_manager_18cb50_idx'),
        ),
    ]
