# Generated by Django 5.2.11 on 2026-04-10 02:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_address_shop_city_shop_country_shop_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Affectation en cours')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='shop',
            name='shops_shop_manager_18cb50_idx',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='manager',
        ),
        migrations.AddField(
            model_name='shop',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'SHOP_MANAGER'}, related_name='managed_shops', to=settings.AUTH_USER_MODEL, verbose_name='Managers'),
        ),
        migrations.AddField(
            model_name='shopassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Affecté par'),
        ),
        migrations.AddField(
            model_name='shopassignment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shops.shop', verbose_name='Boutique'),
        ),
        migrations.AddField(
            model_name='shopassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Employé'),
        ),
        migrations.AddIndex(
            model_name='shopassignment',
            index=models.Index(fields=['user', 'is_active'], name='shops_shopa_user_id_7d766a_idx'),
        ),
        migrations.AddIndex(
            model_name='shopassignment',
            index=models.Index(fields=['shop', 'is_active'], name='shops_shopa_shop_id_708d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='shopassignment',
            index=models.Index(fields=['start_date'], name='shops_shopa_start_d_cf8815_idx'),
        ),
    ]
