# Generated by Django 5.2.11 on 2026-04-10 05:44

from django.db import migrations


def backfill_managers_m2m(apps, schema_editor):
    """
    Les managers SHOP_MANAGER ont user.shop = leur boutique.
    On peuple le M2M shop.managers avec ces données.
    """
    User = apps.get_model('accounts', 'User')
    Shop = apps.get_model('shops', 'Shop')

    for user in User.objects.filter(role='SHOP_MANAGER', shop__isnull=False):
        shop = Shop.objects.get(id=user.shop_id)
        shop.managers.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_multi_manager_and_shop_assignment'),
    ]

    operations = [
        migrations.RunPython(backfill_managers_m2m, migrations.RunPython.noop),
    ]
