# Generated by Django 5.2.11 on 2026-02-24 23:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0002_shop_address_shop_city_shop_country_shop_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name="Numéro d'inventaire")),
                ('inventory_date', models.DateField(help_text='Date du comptage physique', verbose_name="Date de l'inventaire")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, help_text="Observations générales sur l'inventaire", null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('completed_at', models.DateTimeField(blank=True, help_text="Date où l'inventaire a été marqué comme terminé", null=True, verbose_name='Date de finalisation')),
                ('validated_at', models.DateTimeField(blank=True, help_text="Date où l'inventaire a été validé et les stocks ajustés", null=True, verbose_name='Date de validation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='shops.shop', verbose_name='Boutique')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-inventory_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.IntegerField(help_text='Stock théorique selon le système', verbose_name='Quantité attendue')),
                ('counted_quantity', models.IntegerField(blank=True, help_text='Stock réel compté physiquement', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité comptée')),
                ('is_counted', models.BooleanField(default=False, help_text='Le produit a-t-il été compté?', verbose_name='Compté')),
                ('notes', models.TextField(blank=True, help_text='Observations sur ce produit', null=True, verbose_name='Notes')),
                ('counted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de comptage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lines_counted', to=settings.AUTH_USER_MODEL, verbose_name='Compté par')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventories.inventory', verbose_name='Inventaire')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lines', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'ordering': ['product__name'],
            },
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['shop', 'inventory_date'], name='inventories_shop_id_9386af_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['status'], name='inventories_status_5af008_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['-inventory_date'], name='inventories_invento_637af8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryline',
            index=models.Index(fields=['inventory', 'product'], name='inventories_invento_5556b1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryline',
            index=models.Index(fields=['is_counted'], name='inventories_is_coun_301d2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryline',
            unique_together={('inventory', 'product')},
        ),
    ]
