# Generated by Django 5.2.11 on 2026-02-24 23:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0002_shop_address_shop_city_shop_country_shop_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité en stock')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product', verbose_name='Produit')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='shops.shop', verbose_name='Boutique')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_updates', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['shop', 'product'],
                'indexes': [models.Index(fields=['product', 'shop'], name='stocks_stoc_product_e1f8e9_idx'), models.Index(fields=['shop'], name='stocks_stoc_shop_id_895fa5_idx'), models.Index(fields=['quantity'], name='stocks_stoc_quantit_2fa7fa_idx')],
                'unique_together': {('product', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Entrée (Réception)'), ('exit', 'Sortie (Vente)'), ('transfer_out', 'Transfert sortant'), ('transfer_in', 'Transfert entrant'), ('adjustment', 'Ajustement manuel'), ('return', 'Retour'), ('damage', 'Casse/Perte'), ('inventory', 'Ajustement inventaire')], max_length=20, verbose_name='Type de mouvement')),
                ('quantity', models.IntegerField(help_text='Positif pour ajout, négatif pour retrait', verbose_name='Quantité')),
                ('quantity_before', models.IntegerField(help_text='Stock avant ce mouvement', verbose_name='Quantité avant')),
                ('quantity_after', models.IntegerField(help_text='Stock après ce mouvement', verbose_name='Quantité après')),
                ('reference', models.CharField(blank=True, help_text='Numéro de commande, bon de livraison, etc.', max_length=100, null=True, verbose_name='Référence')),
                ('reason', models.TextField(blank=True, help_text='Raison du mouvement', null=True, verbose_name='Motif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat ou de vente au moment du mouvement", max_digits=10, null=True, verbose_name='Prix unitaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='Produit')),
                ('related_shop', models.ForeignKey(blank=True, help_text='Pour les transferts: boutique source ou destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_movements', to='shops.shop', verbose_name='Boutique liée')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='shops.shop', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'shop'], name='stocks_stoc_product_a2773e_idx'), models.Index(fields=['shop', 'created_at'], name='stocks_stoc_shop_id_1db974_idx'), models.Index(fields=['movement_type'], name='stocks_stoc_movemen_9d58c9_idx'), models.Index(fields=['-created_at'], name='stocks_stoc_created_d5d406_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Numéro de transfert')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_transit', 'En transit'), ('received', 'Reçu'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de réception')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('from_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='shops.shop', verbose_name='Boutique source')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='products.product', verbose_name='Produit')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL, verbose_name='Reçu par')),
                ('to_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='shops.shop', verbose_name='Boutique destination')),
            ],
            options={
                'verbose_name': 'Transfert de stock',
                'verbose_name_plural': 'Transferts de stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='stocks_stoc_referen_b3917b_idx'), models.Index(fields=['from_shop', 'to_shop'], name='stocks_stoc_from_sh_0318ec_idx'), models.Index(fields=['status'], name='stocks_stoc_status_bc3e45_idx'), models.Index(fields=['-created_at'], name='stocks_stoc_created_0054f2_idx')],
            },
        ),
    ]
